version: "3.8"

services:
  php:
    image: php:8.1-fpm
    container_name: studi_restaurant_php
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - DATABASE_URL=mysql://restaurant_user:restaurant_password@db:3306/restaurant_db
      - APP_ENV=dev
    depends_on:
      - db
    networks:
      - studi_network

  db:
    image: mysql:8.0
    container_name: studi_restaurant_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: restaurant_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - studi_network

  nginx:
    image: nginx:latest
    container_name: studi_restaurant_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - studi_network

  composer:
    image: composer:latest
    container_name: studi_restaurant_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
      - composer_cache:/tmp/cache
    command: install --no-interaction --prefer-dist
    networks:
      - studi_network

volumes:
  db_data:
  composer_cache:

networks:
  studi_network:
    driver: bridge
